{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_service_line\", \"dim_client_type\", \"dim_industry\", \"dim_new_vs_existing\", \"dim_lead_source\", \"dim_status\", \"fact_opportunities\", \"analytical_training_summary\", \"analytical_job_results\", \"analytical_test_results\", \"analytical_pipeline_results\", \"log_build_runs\", \"_Measures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "dataSources": [
      {
        "name": "SqlServer localhost\\SQLEXPRESS01 PipelineAnalytics",
        "connectionDetails": {
          "address": {
            "database": "PipelineAnalytics",
            "server": "localhost\\SQLEXPRESS01"
          },
          "authentication": null,
          "protocol": "tds",
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "pbi_user",
          "kind": "SQL",
          "path": "localhost\\SQLEXPRESS01;PipelineAnalytics"
        },
        "type": "structured"
      }
    ],
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "fact_opportunities_ServiceLineKey_to_dim_service_line_ServiceLineKey",
        "fromColumn": "ServiceLineKey",
        "fromTable": "fact_opportunities",
        "toColumn": "ServiceLineKey",
        "toTable": "dim_service_line"
      },
      {
        "name": "fact_opportunities_ClientTypeKey_to_dim_client_type_ClientTypeKey",
        "fromColumn": "ClientTypeKey",
        "fromTable": "fact_opportunities",
        "toColumn": "ClientTypeKey",
        "toTable": "dim_client_type"
      },
      {
        "name": "fact_opportunities_IndustryKey_to_dim_industry_IndustryKey",
        "fromColumn": "IndustryKey",
        "fromTable": "fact_opportunities",
        "toColumn": "IndustryKey",
        "toTable": "dim_industry"
      },
      {
        "name": "fact_opportunities_NewVsExistingKey_to_dim_new_vs_existing_NewVsExistingKey",
        "fromColumn": "NewVsExistingKey",
        "fromTable": "fact_opportunities",
        "toColumn": "NewVsExistingKey",
        "toTable": "dim_new_vs_existing"
      },
      {
        "name": "fact_opportunities_LeadSourceKey_to_dim_lead_source_LeadSourceKey",
        "fromColumn": "LeadSourceKey",
        "fromTable": "fact_opportunities",
        "toColumn": "LeadSourceKey",
        "toTable": "dim_lead_source"
      },
      {
        "name": "fact_opportunities_StatusKey_to_dim_status_StatusKey",
        "fromColumn": "StatusKey",
        "fromTable": "fact_opportunities",
        "toColumn": "StatusKey",
        "toTable": "dim_status"
      },
      {
        "name": "analytical_job_results_OpportunityID_to_fact_opportunities_OpportunityID",
        "fromColumn": "OpportunityID",
        "fromTable": "analytical_job_results",
        "toColumn": "OpportunityID",
        "toTable": "fact_opportunities"
      },
      {
        "name": "analytical_test_results_OpportunityID_to_fact_opportunities_OpportunityID",
        "fromColumn": "OpportunityID",
        "fromTable": "analytical_test_results",
        "toColumn": "OpportunityID",
        "toTable": "fact_opportunities"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_service_line",
        "columns": [
          {
            "name": "ServiceLineKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "8a197570-e6c5-403e-b3e5-f024a2658c91",
            "sourceColumn": "ServiceLineKey",
            "summarizeBy": "none"
          },
          {
            "name": "ServiceLineName",
            "dataType": "string",
            "lineageTag": "af2755cf-bbfc-4de5-9c4a-5ce17dd33db4",
            "sourceColumn": "ServiceLineName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "446ecc0c-38c1-4ab5-a56f-484a2c689671",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"dim_service_line\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_client_type",
        "columns": [
          {
            "name": "ClientTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "d9b7119c-f562-4aad-92b9-ca2abcf89688",
            "sourceColumn": "ClientTypeKey",
            "summarizeBy": "none"
          },
          {
            "name": "ClientTypeName",
            "dataType": "string",
            "lineageTag": "7dfb4f6e-6635-408e-a1f9-1ceabbb62e12",
            "sourceColumn": "ClientTypeName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8cc17449-4908-4149-afa0-aa3cc2c5efcd",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"dim_client_type\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_industry",
        "columns": [
          {
            "name": "IndustryKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "cce75d30-edbe-4861-ac0d-59e48fa94da0",
            "sourceColumn": "IndustryKey",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryName",
            "dataType": "string",
            "lineageTag": "296a5d31-e3af-4059-8dbf-7c5e09e4efe9",
            "sourceColumn": "IndustryName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0949ad81-bcc3-4628-90ac-795e76eec17d",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"dim_industry\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_new_vs_existing",
        "columns": [
          {
            "name": "NewVsExistingKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "5fb6ad67-0c1e-472f-804f-4da5f7d255f1",
            "sourceColumn": "NewVsExistingKey",
            "summarizeBy": "none"
          },
          {
            "name": "NewVsExistingName",
            "dataType": "string",
            "lineageTag": "0eaf67be-d3fc-4aa5-952e-6035d0669a66",
            "sourceColumn": "NewVsExistingName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6fb3a284-3ebb-424e-a161-ee6094c34fae",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"dim_new_vs_existing\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_lead_source",
        "columns": [
          {
            "name": "LeadSourceKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "f2fe3d24-d996-41d0-aa20-e6ff5fab7798",
            "sourceColumn": "LeadSourceKey",
            "summarizeBy": "none"
          },
          {
            "name": "LeadSourceName",
            "dataType": "string",
            "lineageTag": "183f2da0-5fbe-4c65-80ab-81f0944b7a36",
            "sourceColumn": "LeadSourceName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5bf8a484-a666-4b53-8ffc-f6ad061402e4",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"dim_lead_source\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_status",
        "columns": [
          {
            "name": "StatusKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "be218ef3-e7b5-4da4-a62d-eebd3cb913af",
            "sourceColumn": "StatusKey",
            "summarizeBy": "none"
          },
          {
            "name": "StatusName",
            "dataType": "string",
            "lineageTag": "50731cd2-ae7c-423b-a950-f487f9e0428c",
            "sourceColumn": "StatusName",
            "summarizeBy": "none"
          },
          {
            "name": "StatusDescription",
            "dataType": "string",
            "lineageTag": "a929491d-97e7-4156-a1b7-399431884abd",
            "sourceColumn": "StatusDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "99a3f278-4143-4d77-939e-c497df515be6",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"dim_status\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_opportunities",
        "columns": [
          {
            "name": "OpportunityID",
            "dataType": "string",
            "lineageTag": "d4338b47-4aa4-4cf7-8c16-1c913a1b867a",
            "sourceColumn": "OpportunityID",
            "summarizeBy": "none"
          },
          {
            "name": "ServiceLineKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "799d51cc-0238-4084-8a67-a14684cb9555",
            "sourceColumn": "ServiceLineKey",
            "summarizeBy": "none"
          },
          {
            "name": "ClientTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "a87b5943-427e-4197-b0d7-6830a1144bae",
            "sourceColumn": "ClientTypeKey",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "34f9e922-aca1-4b4f-868c-56f2e4ea0f0a",
            "sourceColumn": "IndustryKey",
            "summarizeBy": "none"
          },
          {
            "name": "NewVsExistingKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "d67902d5-db9c-4cc4-919e-02aec50d02d1",
            "sourceColumn": "NewVsExistingKey",
            "summarizeBy": "none"
          },
          {
            "name": "LeadSourceKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "526f8d36-abaa-4223-a320-c2d325efd083",
            "sourceColumn": "LeadSourceKey",
            "summarizeBy": "none"
          },
          {
            "name": "StatusKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "d6872ee6-854e-4a9b-97b8-d8e4970c2f63",
            "sourceColumn": "StatusKey",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "a2daac58-1cdd-4f3e-b76f-b7423a72e540",
            "sourceColumn": "CreatedDate",
            "summarizeBy": "none"
          },
          {
            "name": "SoldDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "ee22ac54-eedf-463c-b6a4-c52c3c7d0d10",
            "sourceColumn": "SoldDate",
            "summarizeBy": "none"
          },
          {
            "name": "ClosedLostDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "0e5459a4-4c9f-411a-a119-1da262c76549",
            "sourceColumn": "ClosedLostDate",
            "summarizeBy": "none"
          },
          {
            "name": "StartDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "af358aa3-2402-4ada-80ee-b30e53ffe182",
            "sourceColumn": "StartDate",
            "summarizeBy": "none"
          },
          {
            "name": "Pct50CompleteDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "3edf8533-c544-40ba-afda-ab4851d95614",
            "sourceColumn": "Pct50CompleteDate",
            "summarizeBy": "none"
          },
          {
            "name": "Pct100CompleteDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e0baafbf-ba3e-4b89-8f5c-7d811b406b15",
            "sourceColumn": "Pct100CompleteDate",
            "summarizeBy": "none"
          },
          {
            "name": "ResolutionDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "429eb243-19e3-4977-86a1-bc2b42ece0bd",
            "sourceColumn": "ResolutionDate",
            "summarizeBy": "none"
          },
          {
            "name": "NetFees",
            "dataType": "double",
            "formatString": "$#,##0",
            "lineageTag": "ff032a1e-939d-42e7-960a-ebcfa8d467ce",
            "sourceColumn": "NetFees",
            "summarizeBy": "sum"
          },
          {
            "name": "MarginPct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0%",
            "lineageTag": "646926df-8ddd-467a-8465-6284d4241e9d",
            "sourceColumn": "MarginPct",
            "summarizeBy": "sum"
          },
          {
            "name": "MarginDollars",
            "dataType": "double",
            "formatString": "$#,##0",
            "lineageTag": "f5bffbf1-abb7-4fd4-8938-f9f1fb229a95",
            "sourceColumn": "MarginDollars",
            "summarizeBy": "sum"
          },
          {
            "name": "DaysSellToStart",
            "dataType": "int64",
            "lineageTag": "7eb5ecc6-af8e-4698-a2c3-592f876323f5",
            "sourceColumn": "DaysSellToStart",
            "summarizeBy": "average"
          },
          {
            "name": "DaysStartTo50Pct",
            "dataType": "int64",
            "lineageTag": "bf25c143-e2ac-4cc3-8651-05303a3396cc",
            "sourceColumn": "DaysStartTo50Pct",
            "summarizeBy": "average"
          },
          {
            "name": "DaysStartTo100Pct",
            "dataType": "int64",
            "lineageTag": "3e8daa12-c37f-4217-8e9f-9ddbadf345ad",
            "sourceColumn": "DaysStartTo100Pct",
            "summarizeBy": "average"
          },
          {
            "name": "LoadTimestamp",
            "dataType": "dateTime",
            "isHidden": true,
            "lineageTag": "999ef38f-035a-4f01-9410-f7cadd555b45",
            "sourceColumn": "LoadTimestamp",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b8847f52-f853-4376-bf72-84a022698070",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"fact_opportunities\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "analytical_training_summary",
        "columns": [
          {
            "name": "TrainingSummaryKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9acd92ee-8e2e-4b2c-ba01-ba6b9dac47d2",
            "sourceColumn": "TrainingSummaryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SegmentKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "bbbbddf5-10e3-4447-a505-b99f78f56af1",
            "sourceColumn": "SegmentKey",
            "summarizeBy": "none"
          },
          {
            "name": "BuildRunKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "b9d5674b-23d0-4879-a79b-962410a1afad",
            "sourceColumn": "BuildRunKey",
            "summarizeBy": "none"
          },
          {
            "name": "OutcomeName",
            "dataType": "string",
            "lineageTag": "0bde6ce8-c74a-4039-814b-318dfb57f8f8",
            "sourceColumn": "OutcomeName",
            "summarizeBy": "none"
          },
          {
            "name": "OutcomeEstimate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f49b72a6-f974-410e-be8e-3b85c0c3885b",
            "sourceColumn": "OutcomeEstimate",
            "summarizeBy": "sum"
          },
          {
            "name": "ObservationCount",
            "dataType": "int64",
            "lineageTag": "4a495bb2-6f5e-4efc-8536-5a25028ac15e",
            "sourceColumn": "ObservationCount",
            "summarizeBy": "sum"
          },
          {
            "name": "GranularityLevel",
            "dataType": "int64",
            "lineageTag": "35ebe24c-f27d-48f6-9c0f-0dda39b691cb",
            "sourceColumn": "GranularityLevel",
            "summarizeBy": "none"
          },
          {
            "name": "CategoriesDropped",
            "dataType": "int64",
            "lineageTag": "706dfb43-0edd-4a3f-b727-aa8078eec0ee",
            "sourceColumn": "CategoriesDropped",
            "summarizeBy": "none"
          },
          {
            "name": "Cat1Dropped",
            "dataType": "boolean",
            "lineageTag": "d4daaf36-f684-462d-bfa4-d91e394095ed",
            "sourceColumn": "Cat1Dropped",
            "summarizeBy": "none"
          },
          {
            "name": "Cat2Dropped",
            "dataType": "boolean",
            "lineageTag": "de8a7758-0753-42fb-82c6-5751e641a1d8",
            "sourceColumn": "Cat2Dropped",
            "summarizeBy": "none"
          },
          {
            "name": "Cat3Dropped",
            "dataType": "boolean",
            "lineageTag": "ad1a94f0-394c-405a-bb9e-9681eca7e5c3",
            "sourceColumn": "Cat3Dropped",
            "summarizeBy": "none"
          },
          {
            "name": "Cat4Dropped",
            "dataType": "boolean",
            "lineageTag": "6fd41022-2762-43ac-9c22-18c6ad6152c9",
            "sourceColumn": "Cat4Dropped",
            "summarizeBy": "none"
          },
          {
            "name": "Cat5Dropped",
            "dataType": "boolean",
            "lineageTag": "47c85ac5-18fe-45c0-ae1f-085877107710",
            "sourceColumn": "Cat5Dropped",
            "summarizeBy": "none"
          },
          {
            "name": "StatusName",
            "dataType": "string",
            "lineageTag": "a35460be-829b-4d70-b3fe-5414c618cf8d",
            "sourceColumn": "StatusName",
            "summarizeBy": "none"
          },
          {
            "name": "ServiceLineName",
            "dataType": "string",
            "lineageTag": "00cded8d-5f01-4723-a380-f8847f21c1db",
            "sourceColumn": "ServiceLineName",
            "summarizeBy": "none"
          },
          {
            "name": "ClientTypeName",
            "dataType": "string",
            "lineageTag": "5174ce95-4de2-4eb9-81c3-74a684ab182d",
            "sourceColumn": "ClientTypeName",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryName",
            "dataType": "string",
            "lineageTag": "3b95f5d3-9993-4600-bf01-bff02b4cd7da",
            "sourceColumn": "IndustryName",
            "summarizeBy": "none"
          },
          {
            "name": "NewVsExistingName",
            "dataType": "string",
            "lineageTag": "162fbb09-9b83-4b7f-a856-07d80827cb27",
            "sourceColumn": "NewVsExistingName",
            "summarizeBy": "none"
          },
          {
            "name": "LeadSourceName",
            "dataType": "string",
            "lineageTag": "746d163a-8f3f-4605-9ce4-dd6251be9904",
            "sourceColumn": "LeadSourceName",
            "summarizeBy": "none"
          },
          {
            "name": "SegmentLabel",
            "dataType": "string",
            "lineageTag": "c705315c-3189-4838-a94d-d38a3bd289b2",
            "sourceColumn": "SegmentLabel",
            "summarizeBy": "none"
          },
          {
            "name": "DroppedCategoriesLabel",
            "dataType": "string",
            "lineageTag": "10f767dd-e01a-4071-b524-97fdbf3aad04",
            "sourceColumn": "DroppedCategoriesLabel",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "83708652-18a0-4abe-a792-768092ff42ee",
        "measures": [
          {
            "name": "Seg Count",
            "expression": "DISTINCTCOUNT(analytical_training_summary[SegmentLabel])",
            "formatString": "0",
            "lineageTag": "645944da-5e1e-417e-b7a7-c82c19b36522"
          },
          {
            "name": "Avg Obs Per Segment",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(analytical_training_summary[ObservationCount])",
            "lineageTag": "afe0b124-8543-4dbc-9e80-0431899fd0cc"
          },
          {
            "name": "Segs With Drops",
            "expression": "CALCULATE(DISTINCTCOUNT(analytical_training_summary[SegmentLabel]), analytical_training_summary[CategoriesDropped] > 0)",
            "formatString": "0",
            "lineageTag": "6140fbb9-656b-445f-ab96-f781496fbb89"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"analytical_training_summary\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "analytical_job_results",
        "columns": [
          {
            "name": "OpportunityID",
            "dataType": "string",
            "lineageTag": "72193b28-5363-417d-a270-ac96cb9d9029",
            "sourceColumn": "OpportunityID",
            "summarizeBy": "none"
          },
          {
            "name": "SegmentKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "dc35a7a1-4e17-4b5b-a8b7-8071cfd3aec5",
            "sourceColumn": "SegmentKey",
            "summarizeBy": "none"
          },
          {
            "name": "BuildRunKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "62946c13-507c-45a9-a040-a1274c7e543e",
            "sourceColumn": "BuildRunKey",
            "summarizeBy": "none"
          },
          {
            "name": "EstimatedWinPct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0%",
            "lineageTag": "1537c6f8-ee53-4ae8-9f88-6f48d0770488",
            "sourceColumn": "EstimatedWinPct",
            "summarizeBy": "sum"
          },
          {
            "name": "EstimatedNetFees",
            "dataType": "double",
            "formatString": "$#,##0",
            "lineageTag": "b0a60c95-0bfc-4876-83e3-82da501f6977",
            "sourceColumn": "EstimatedNetFees",
            "summarizeBy": "sum"
          },
          {
            "name": "EstimatedMarginPct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0%",
            "lineageTag": "c200ac6b-99f0-4f6e-92f6-ba8dd051496f",
            "sourceColumn": "EstimatedMarginPct",
            "summarizeBy": "sum"
          },
          {
            "name": "EstimatedMarginDollars",
            "dataType": "double",
            "formatString": "$#,##0",
            "lineageTag": "77b2b9c2-265a-4484-bd9a-33b1de0d98b2",
            "sourceColumn": "EstimatedMarginDollars",
            "summarizeBy": "sum"
          },
          {
            "name": "EstimatedSellDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "436e490e-bd5b-428d-aa52-174fd980caff",
            "sourceColumn": "EstimatedSellDate",
            "summarizeBy": "none"
          },
          {
            "name": "EstimatedStartDate",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "b3db5fe8-2609-442a-bdf5-bd227d76be5e",
            "sourceColumn": "EstimatedStartDate",
            "summarizeBy": "none"
          },
          {
            "name": "EstimatedPct50Date",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "17ded1d1-20b0-40c6-a8d6-717758b45236",
            "sourceColumn": "EstimatedPct50Date",
            "summarizeBy": "none"
          },
          {
            "name": "EstimatedPct100Date",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "abdfd70d-35d0-4aa9-98ca-dc63700a71d2",
            "sourceColumn": "EstimatedPct100Date",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetType",
            "dataType": "string",
            "lineageTag": "4771cf11-4c21-40ac-a353-5231765326b9",
            "sourceColumn": "DatasetType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "89576908-40ab-43ae-86ac-7b5c88deb58c",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"analytical_job_results\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "analytical_test_results",
        "columns": [
          {
            "name": "TestResultKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "7001c469-1d87-4d8b-af31-b45fb106b65d",
            "sourceColumn": "TestResultKey",
            "summarizeBy": "none"
          },
          {
            "name": "OpportunityID",
            "dataType": "string",
            "lineageTag": "0285019e-af39-419a-8439-3f4ac9512184",
            "sourceColumn": "OpportunityID",
            "summarizeBy": "none"
          },
          {
            "name": "SegmentKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "c3c509b6-6518-4cff-9a1a-836246f20b6d",
            "sourceColumn": "SegmentKey",
            "summarizeBy": "none"
          },
          {
            "name": "BuildRunKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "1d908670-f010-4da1-b89a-edba4bf1a164",
            "sourceColumn": "BuildRunKey",
            "summarizeBy": "none"
          },
          {
            "name": "OutcomeName",
            "dataType": "string",
            "lineageTag": "dfed2c18-a9e6-46ba-b6da-695ae96ed407",
            "sourceColumn": "OutcomeName",
            "summarizeBy": "none"
          },
          {
            "name": "PredictedValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f1f1b6b4-45d4-4238-ab09-c8919acbe0b6",
            "sourceColumn": "PredictedValue",
            "summarizeBy": "sum"
          },
          {
            "name": "ActualValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "41aa6804-1b43-406e-ad1c-34e977a52bfd",
            "sourceColumn": "ActualValue",
            "summarizeBy": "sum"
          },
          {
            "name": "Error",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "266f10ca-4d02-451f-9eb5-b6871d2980b2",
            "sourceColumn": "Error",
            "summarizeBy": "sum"
          },
          {
            "name": "AbsoluteError",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "16efca48-4e9b-43fb-a080-5478c6c57ec3",
            "sourceColumn": "AbsoluteError",
            "summarizeBy": "sum"
          },
          {
            "name": "SquaredError",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ade60d72-9f4b-4316-bda3-bb27af4ee25a",
            "sourceColumn": "SquaredError",
            "summarizeBy": "sum"
          },
          {
            "name": "PercentageError",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0%",
            "lineageTag": "7ea469e2-20fd-49e0-80cb-c16edc4ea711",
            "sourceColumn": "PercentageError",
            "summarizeBy": "sum"
          },
          {
            "name": "GranularityLevel",
            "dataType": "int64",
            "lineageTag": "93f53a39-7013-4892-ad36-ec06c0b7557f",
            "sourceColumn": "GranularityLevel",
            "summarizeBy": "none"
          },
          {
            "name": "CategoriesDropped",
            "dataType": "int64",
            "lineageTag": "b217072f-38a3-4390-8f7f-16300c7b36b8",
            "sourceColumn": "CategoriesDropped",
            "summarizeBy": "none"
          },
          {
            "name": "StatusName",
            "dataType": "string",
            "lineageTag": "c3dead80-23e0-4a15-86a9-e122dddcaf3c",
            "sourceColumn": "StatusName",
            "summarizeBy": "none"
          },
          {
            "name": "ServiceLineName",
            "dataType": "string",
            "lineageTag": "9b1b0763-19b4-43b4-b74c-0f5d4ced1ea5",
            "sourceColumn": "ServiceLineName",
            "summarizeBy": "none"
          },
          {
            "name": "ClientTypeName",
            "dataType": "string",
            "lineageTag": "76790b73-703f-4c60-8fd0-dc4de2f0f613",
            "sourceColumn": "ClientTypeName",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryName",
            "dataType": "string",
            "lineageTag": "4f300687-267a-416f-b072-f487f34b6c45",
            "sourceColumn": "IndustryName",
            "summarizeBy": "none"
          },
          {
            "name": "NewVsExistingName",
            "dataType": "string",
            "lineageTag": "aee52337-7a16-4c8a-88fc-8f736edb22c8",
            "sourceColumn": "NewVsExistingName",
            "summarizeBy": "none"
          },
          {
            "name": "LeadSourceName",
            "dataType": "string",
            "lineageTag": "056da5ea-cae6-46d3-8216-1546967148a0",
            "sourceColumn": "LeadSourceName",
            "summarizeBy": "none"
          },
          {
            "name": "SegmentLabel",
            "dataType": "string",
            "lineageTag": "72b17610-255f-4239-8a6b-e822ea50b142",
            "sourceColumn": "SegmentLabel",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "65dc6da6-627f-4aec-af4a-a46b1f0ff1ad",
        "measures": [
          {
            "name": "Test RMSE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SQRT(AVERAGE(analytical_test_results[SquaredError]))",
            "lineageTag": "600c6666-cb53-4b66-926c-d6c8c0362e18"
          },
          {
            "name": "Test Mean Error",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(analytical_test_results[Error])",
            "lineageTag": "9df74ea8-6226-4f20-8deb-e1aeca3aaf7d"
          },
          {
            "name": "Test MAE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(analytical_test_results[AbsoluteError])",
            "lineageTag": "ace4f394-a167-47f0-a510-403acd7c004d"
          },
          {
            "name": "Test Expected Wins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(analytical_test_results[PredictedValue]), analytical_test_results[OutcomeName] = \"WinPct\")",
            "lineageTag": "01c666ed-f860-4060-92ea-3fccae0b17aa"
          },
          {
            "name": "Test Actual Wins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(analytical_test_results[ActualValue]), analytical_test_results[OutcomeName] = \"WinPct\")",
            "lineageTag": "e2e6d50f-2635-4d4e-b06c-cac58872628b"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"analytical_test_results\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "analytical_pipeline_results",
        "columns": [
          {
            "name": "PipelineResultKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "28c9fc23-3b5e-4684-89f1-0d277dc3ffae",
            "sourceColumn": "PipelineResultKey",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodMonth",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "MMM YYYY",
            "lineageTag": "21228f57-d74f-4148-ae37-8ff202f38b33",
            "sourceColumn": "PeriodMonth",
            "summarizeBy": "none"
          },
          {
            "name": "EstimatedJobCount",
            "dataType": "int64",
            "lineageTag": "89379ea5-2ae6-4d69-a9fb-d21bac9d5200",
            "sourceColumn": "EstimatedJobCount",
            "summarizeBy": "sum"
          },
          {
            "name": "EstimatedNetFees",
            "dataType": "double",
            "formatString": "$#,##0",
            "lineageTag": "98359856-184f-4843-80ac-0ff329043db4",
            "sourceColumn": "EstimatedNetFees",
            "summarizeBy": "sum"
          },
          {
            "name": "EstimatedMarginDollars",
            "dataType": "double",
            "formatString": "$#,##0",
            "lineageTag": "4b534c4d-d560-49f9-b948-69cbd04e1c5c",
            "sourceColumn": "EstimatedMarginDollars",
            "summarizeBy": "sum"
          },
          {
            "name": "MedianPct50Date",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "cfc56481-0403-4351-8e61-cda5d6ab8f39",
            "sourceColumn": "MedianPct50Date",
            "summarizeBy": "none"
          },
          {
            "name": "MedianPct100Date",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "9fd47d0b-9347-4494-ab06-0f2f99d9ba96",
            "sourceColumn": "MedianPct100Date",
            "summarizeBy": "none"
          },
          {
            "name": "BuildRunKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "d9b03783-5c0e-490a-8549-8dc989bca51f",
            "sourceColumn": "BuildRunKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d42a9dc2-4d56-4a7e-ae77-18d5de5cfff0",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"analytical_pipeline_results\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "log_build_runs",
        "columns": [
          {
            "name": "BuildRunKey",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "4d8006f8-d3d8-4b2e-a5d6-a08f8fd31c33",
            "sourceColumn": "BuildRunKey",
            "summarizeBy": "none"
          },
          {
            "name": "RunTimestamp",
            "dataType": "dateTime",
            "lineageTag": "6ffc4116-6379-4f9e-bf62-11e48e358ede",
            "sourceColumn": "RunTimestamp",
            "summarizeBy": "none"
          },
          {
            "name": "MinJobsPerSegment",
            "dataType": "int64",
            "lineageTag": "32d0c723-abac-42e7-8963-f65b9cf647ac",
            "sourceColumn": "MinJobsPerSegment",
            "summarizeBy": "none"
          },
          {
            "name": "TrainingStart",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "8847ddc2-76e7-47c6-8349-c9da38395b26",
            "sourceColumn": "TrainingStart",
            "summarizeBy": "none"
          },
          {
            "name": "TrainingEnd",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "4d01edcd-9471-4b80-848f-9b4d80e9ff92",
            "sourceColumn": "TrainingEnd",
            "summarizeBy": "none"
          },
          {
            "name": "TestStart",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "702f5d6f-6ba0-4968-a4f7-78b64b07152e",
            "sourceColumn": "TestStart",
            "summarizeBy": "none"
          },
          {
            "name": "TestEnd",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "8663b797-2f86-4b1b-bbdc-ad8de9389acf",
            "sourceColumn": "TestEnd",
            "summarizeBy": "none"
          },
          {
            "name": "RowsProcessed",
            "dataType": "int64",
            "lineageTag": "68a0b552-6546-4bce-a737-3962706da35f",
            "sourceColumn": "RowsProcessed",
            "summarizeBy": "none"
          },
          {
            "name": "SegmentsBuilt",
            "dataType": "int64",
            "lineageTag": "e7bc14bd-de2e-439d-83d2-004940a5ff84",
            "sourceColumn": "SegmentsBuilt",
            "summarizeBy": "none"
          },
          {
            "name": "JobResultsWritten",
            "dataType": "int64",
            "lineageTag": "db98fe7c-889f-4ec1-af56-c13b34bd4a70",
            "sourceColumn": "JobResultsWritten",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "dataType": "string",
            "lineageTag": "1bca4717-6401-4952-9328-289d32c0de14",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "StatusMessage",
            "dataType": "string",
            "lineageTag": "cac74751-7cdf-4b93-aa6a-5b67dcfd2766",
            "sourceColumn": "StatusMessage",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "547bec13-8342-4616-b181-e88a10bac62c",
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\\SQLEXPRESS01\", \"PipelineAnalytics\"),",
                "    data = Source{[Schema=\"dbo\",Item=\"log_build_runs\"]}[Data]",
                "in",
                "    data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "columns": [
          {
            "name": "Placeholder",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9c6af9d8-246e-4606-b187-2a586e1a38fb",
            "sourceColumn": "Placeholder"
          }
        ],
        "isHidden": true,
        "lineageTag": "8e739718-f19b-4d2d-b8a7-2d60662638e8",
        "measures": [
          {
            "name": "SSE",
            "description": "Sum of Squared Errors. Weights large misses more heavily than MAE.",
            "displayFolder": "Error Metrics",
            "expression": "SUMX(analytical_test_results, analytical_test_results[SquaredError])",
            "formatString": "#,##0.00",
            "lineageTag": "c8814546-6a53-43ee-abfb-51652f818dfa"
          },
          {
            "name": "MSE",
            "description": "Mean Squared Error — average squared prediction error per record.",
            "displayFolder": "Error Metrics",
            "expression": "AVERAGEX(analytical_test_results, analytical_test_results[SquaredError])",
            "formatString": "#,##0.00",
            "lineageTag": "c56fa198-c298-4d38-b13c-97c5460ade55"
          },
          {
            "name": "RMSE",
            "description": "Root Mean Squared Error — in the same units as the outcome. Lower is better.",
            "displayFolder": "Error Metrics",
            "expression": "SQRT(AVERAGEX(analytical_test_results, analytical_test_results[SquaredError]))",
            "formatString": "#,##0.00",
            "lineageTag": "8098ff15-68c7-4480-81fc-dda83eabefac"
          },
          {
            "name": "MAE",
            "description": "Mean Absolute Error — average size of prediction error regardless of direction.",
            "displayFolder": "Error Metrics",
            "expression": "AVERAGEX(analytical_test_results, analytical_test_results[AbsoluteError])",
            "formatString": "#,##0.00",
            "lineageTag": "8f068187-7893-4976-a256-21d237f9628e"
          },
          {
            "name": "MAPE",
            "description": "Mean Absolute Percentage Error. Normalises error by outcome scale for cross-outcome comparison.",
            "displayFolder": "Error Metrics",
            "expression": "AVERAGEX(FILTER(analytical_test_results, NOT ISBLANK(analytical_test_results[PercentageError])), ABS(analytical_test_results[PercentageError]))",
            "formatString": "0.0%",
            "lineageTag": "3886a831-9046-4bac-ab77-2626f5c53b9b"
          },
          {
            "name": "Mean Error (Bias)",
            "description": "Mean Error — directional bias. Positive = overestimate, negative = underestimate.",
            "displayFolder": "Error Metrics",
            "expression": "AVERAGEX(analytical_test_results, analytical_test_results[Error])",
            "formatString": "+#,##0.00;-#,##0.00;0.00",
            "lineageTag": "1749d879-488a-4073-8874-d3b6126c9d6e"
          },
          {
            "name": "Expected Wins",
            "description": "Sum of predicted win probabilities — the number of wins the model expected.",
            "displayFolder": "Win % Calibration",
            "expression": "CALCULATE(SUM(analytical_test_results[PredictedValue]), analytical_test_results[OutcomeName] = \"WinPct\")",
            "formatString": "#,##0.0",
            "lineageTag": "ecc4310c-35bf-4689-a02e-80f1194e5401"
          },
          {
            "name": "Actual Wins",
            "description": "Actual number of won opportunities in the test dataset.",
            "displayFolder": "Win % Calibration",
            "expression": "CALCULATE(SUM(analytical_test_results[ActualValue]), analytical_test_results[OutcomeName] = \"WinPct\")",
            "formatString": "#,##0",
            "lineageTag": "bedc152d-25f0-45f3-92ef-9505b71aa60d"
          },
          {
            "name": "Win Rate Predicted",
            "description": "Average predicted win probability across test records.",
            "displayFolder": "Win % Calibration",
            "expression": "DIVIDE([Expected Wins], CALCULATE(COUNTROWS(analytical_test_results), analytical_test_results[OutcomeName] = \"WinPct\"))",
            "formatString": "0.0%",
            "lineageTag": "54bc3b2e-8d31-4c53-a038-7a4f7dc7c399"
          },
          {
            "name": "Win Rate Actual",
            "description": "Actual win rate observed in the test dataset.",
            "displayFolder": "Win % Calibration",
            "expression": "DIVIDE([Actual Wins], CALCULATE(COUNTROWS(analytical_test_results), analytical_test_results[OutcomeName] = \"WinPct\"))",
            "formatString": "0.0%",
            "lineageTag": "bb5b8898-6421-49e2-ab42-857e30c7aa5a"
          },
          {
            "name": "Win Rate Calibration Gap",
            "description": "Predicted minus actual win rate. Near zero = well calibrated model.",
            "displayFolder": "Win % Calibration",
            "expression": "[Win Rate Predicted] - [Win Rate Actual]",
            "formatString": "+0.0%;-0.0%;0.0%",
            "lineageTag": "2984b2dc-b4d9-4ddb-8289-17985209babc"
          },
          {
            "name": "Total Estimated Fees",
            "description": "Total estimated net fees across all months in scope.",
            "displayFolder": "Pipeline",
            "expression": "SUM(analytical_pipeline_results[EstimatedNetFees])",
            "formatString": "$#,##0",
            "lineageTag": "cffe9a28-a993-4367-8a3f-246ac590e73c"
          },
          {
            "name": "Total Estimated Margin",
            "description": "Total estimated margin dollars across all months in scope.",
            "displayFolder": "Pipeline",
            "expression": "SUM(analytical_pipeline_results[EstimatedMarginDollars])",
            "formatString": "$#,##0",
            "lineageTag": "383117bc-b507-454d-a801-fcd5069344d8"
          },
          {
            "name": "Total Estimated Jobs",
            "description": "Total estimated number of jobs starting across all months in scope.",
            "displayFolder": "Pipeline",
            "expression": "SUM(analytical_pipeline_results[EstimatedJobCount])",
            "formatString": "#,##0",
            "lineageTag": "c989d368-b6fd-490c-a848-3b8ad2418621"
          },
          {
            "name": "Avg Estimated Margin %",
            "description": "Blended estimated margin percentage across all jobs in scope.",
            "displayFolder": "Pipeline",
            "expression": "DIVIDE([Total Estimated Margin], [Total Estimated Fees])",
            "formatString": "0.0%",
            "lineageTag": "b5c72659-5a56-4111-85ac-183d63377694"
          },
          {
            "name": "Current Pipeline Jobs",
            "description": "Number of opportunities and jobs in the current pipeline.",
            "displayFolder": "Job Predictions",
            "expression": "CALCULATE(COUNTROWS(analytical_job_results), analytical_job_results[DatasetType] = \"Current\")",
            "formatString": "#,##0",
            "lineageTag": "a14a5515-281f-4e1c-9c1f-8b479891b975"
          },
          {
            "name": "Current Pipeline Estimated Fees",
            "description": "Total estimated net fees across current pipeline records.",
            "displayFolder": "Job Predictions",
            "expression": "CALCULATE(SUM(analytical_job_results[EstimatedNetFees]), analytical_job_results[DatasetType] = \"Current\")",
            "formatString": "$#,##0",
            "lineageTag": "fa73c3f8-6111-4e5b-b145-4d8fc3ddfe34"
          },
          {
            "name": "Current Pipeline Estimated Margin",
            "description": "Total estimated margin dollars across current pipeline records.",
            "displayFolder": "Job Predictions",
            "expression": "CALCULATE(SUM(analytical_job_results[EstimatedMarginDollars]), analytical_job_results[DatasetType] = \"Current\")",
            "formatString": "$#,##0",
            "lineageTag": "e20d65ba-17d2-4088-8c7c-cc33ca48003a"
          },
          {
            "name": "Probability-Weighted Fees",
            "description": "Estimated fees weighted by win probability — expected value of the open opportunity pipeline.",
            "displayFolder": "Job Predictions",
            "expression": "SUMX(FILTER(analytical_job_results, analytical_job_results[DatasetType] = \"Current\" && NOT ISBLANK(analytical_job_results[EstimatedWinPct])), analytical_job_results[EstimatedNetFees] * analytical_job_results[EstimatedWinPct])",
            "formatString": "$#,##0",
            "lineageTag": "29f919d8-145d-48c9-bf46-e2c7e684c58d"
          },
          {
            "name": "Total Segments",
            "description": "Total distinct segment-outcome combinations built from training data.",
            "displayFolder": "Training",
            "expression": "DISTINCTCOUNT(analytical_training_summary[SegmentKey])",
            "formatString": "#,##0",
            "lineageTag": "909b8dc9-21fb-42f8-a81e-75c75df8024a"
          },
          {
            "name": "Segments With Dropped Categories",
            "description": "Segments where at least one category was dropped to meet the minimum observation threshold.",
            "displayFolder": "Training",
            "expression": "CALCULATE(DISTINCTCOUNT(analytical_training_summary[SegmentKey]), analytical_training_summary[CategoriesDropped] > 0)",
            "formatString": "#,##0",
            "lineageTag": "99cb32c2-c45f-4c68-b30b-aff17d4ca89d"
          },
          {
            "name": "Avg Observations Per Segment",
            "description": "Average number of historical observations backing each segment estimate.",
            "displayFolder": "Training",
            "expression": "AVERAGE(analytical_training_summary[ObservationCount])",
            "formatString": "#,##0",
            "lineageTag": "40dd36ec-cc51-4305-9acd-fec805a99b64"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows({}, {\"Placeholder\"})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}